In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("array: ", arr)
print("Type: ", type(arr))

array:  [1 2 3 4 5]
Type:  <class 'numpy.ndarray'>


In [3]:
import numpy as np  

# Creating a 2D array
arr = np.array([[10, 20, 30], [40, 50, 60]])

# Checking attributes
print("Array:\n", arr)
print("\nNumber of dimensions:", arr.ndim)  # Should print 2
print("Shape of array:", arr.shape)        # (rows, columns)
print("Total number of elements:", arr.size)  
print("Data type:", arr.dtype)  
print("Size of each element (bytes):", arr.itemsize)  
print("Total memory usage (bytes):", arr.nbytes)  


Array:
 [[10 20 30]
 [40 50 60]]

Number of dimensions: 2
Shape of array: (2, 3)
Total number of elements: 6
Data type: int64
Size of each element (bytes): 8
Total memory usage (bytes): 48


#### Indexing in 1D Arrays

In [4]:
# Creating a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print("First element:", arr[0])   # 10
print("Last element:", arr[-1])   # 50
print("Second element:", arr[1])  # 20

First element: 10
Last element: 50
Second element: 20


#### Indexing in 2D Arrays (Matrices)

In [5]:
# Creating a 2D array
arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

# Accessing elements
print("Element at row 1, col 2:", arr2D[0, 1])  # 2
print("Element at row 3, col 3:", arr2D[2, 2])  # 9


Element at row 1, col 2: 2
Element at row 3, col 3: 9


#### Slicing NumPy Arrays

In [6]:
# 1D Array Slicing
arr = np.array([10, 20, 30, 40, 50])
print("Elements from index 1 to 3:", arr[1:4])  # [20, 30, 40]
print("Every second element:", arr[::2])        # [10, 30, 50]

# 2D Array Slicing
arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

print("First two rows:\n", arr2D[:2, :])   # First two rows
print("First two columns:\n", arr2D[:, :2])  # First two columns


Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
First two rows:
 [[1 2 3]
 [4 5 6]]
First two columns:
 [[1 2]
 [4 5]
 [7 8]]


#### Reshaping Arrays

In [7]:
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping into 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)

print("Original Array:\n", arr)
print("\nReshaped Array (2x3):\n", reshaped_arr)

Original Array:
 [1 2 3 4 5 6]

Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]


#### Using -1 in Reshaping

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Let NumPy calculate the correct number of columns
reshaped_arr = arr.reshape(2, -1)  # 2 rows, auto column calculation

print("Reshaped using -1:\n", reshaped_arr)


Reshaped using -1:
 [[1 2 3]
 [4 5 6]]


#### Flattening an Array

In [10]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten using ravel()
flattened = arr2D.ravel()  # returns a copy of the original array

print("Original 2D Array:\n", arr2D)
print("\nFlattened Array:\n", flattened)


Original 2D Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array:
 [1 2 3 4 5 6]


#### Element-wise Arithmetic Operations

In [11]:
# Creating two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

# Element-wise operations
print("Addition:", arr1 + arr2)  # [11 22 33 44]
print("Subtraction:", arr1 - arr2)  # [-9 -18 -27 -36]
print("Multiplication:", arr1 * arr2)  # [10 40 90 160]
print("Division:", arr1 / arr2)  # [0.1 0.1 0.1 0.1]
print("Power:", arr1 ** 2)  # [1 4 9 16]

Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Power: [ 1  4  9 16]


#### Using NumPy's Universal Functions

In [12]:
arr = np.array([1, 2, 3, 4, 5])

# Applying universal functions
print("Square Root:", np.sqrt(arr))  
print("Exponential (e^x):", np.exp(arr))  
print("Natural Logarithm:", np.log(arr))  
print("Sine values:", np.sin(arr))  
print("Cosine values:", np.cos(arr))  


Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential (e^x): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine values: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine values: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


#### Basic Aggregation Functions

In [13]:
# Creating an array
arr = np.array([10, 20, 30, 40, 50])

# Aggregation operations
print("Sum:", np.sum(arr))         # 150
print("Mean (Average):", np.mean(arr))   # 30.0
print("Minimum:", np.min(arr))     # 10
print("Maximum:", np.max(arr))     # 50
print("Standard Deviation:", np.std(arr))  # 14.14
print("Variance:", np.var(arr))    # 200.0

Sum: 150
Mean (Average): 30.0
Minimum: 10
Maximum: 50
Standard Deviation: 14.142135623730951
Variance: 200.0


#### Aggregations on Multi-Dimensional Arrays

In [15]:
# Creating a 2D array
arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

# Aggregation operations along axis
print("Column-wise Sum (axis=0):", np.sum(arr2D, axis=0))  # [12 15 18]
print("Row-wise Sum (axis=1):", np.sum(arr2D, axis=1))  # [6 15 24]

# axis=0 means sum each column
# axis=1 means sum each row

Column-wise Sum (axis=0): [12 15 18]
Row-wise Sum (axis=1): [ 6 15 24]


#### Sorting NumPy Arrays

In [16]:
# Creating an array
arr = np.array([40, 10, 30, 20, 50])

# Sorting the array
sorted_arr = np.sort(arr)

print("Original Array:", arr)
print("Sorted Array:", sorted_arr)

Original Array: [40 10 30 20 50]
Sorted Array: [10 20 30 40 50]


#### Sorting a 2D Array

In [17]:
arr2D = np.array([[3, 1, 2], 
                  [9, 6, 7], 
                  [4, 5, 8]])

# Sorting along rows (axis=1)
print("Row-wise Sorted:\n", np.sort(arr2D, axis=1))

# Sorting along columns (axis=0)
print("Column-wise Sorted:\n", np.sort(arr2D, axis=0))


Row-wise Sorted:
 [[1 2 3]
 [6 7 9]
 [4 5 8]]
Column-wise Sorted:
 [[3 1 2]
 [4 5 7]
 [9 6 8]]


#### Filtering NumPy Arrays using Boolean Masking

In [18]:
# Creating an array
arr = np.array([10, 20, 30, 40, 50])

# Creating a boolean mask (condition: values > 25)
mask = arr > 25

# Applying the mask to filter values
filtered_arr = arr[mask]

print("Boolean Mask:", mask)  # [False False  True  True  True]
print("Filtered Array:", filtered_arr)  # [30 40 50]


Boolean Mask: [False False  True  True  True]
Filtered Array: [30 40 50]


#### Fancy Indexing (Selecting Specific Elements)

In [19]:
arr = np.array([10, 20, 30, 40, 50])

# Selecting elements at positions 1, 3, and 4
selected = arr[[1, 3, 4]]

print("Selected Elements:", selected)  # [20 40 50]


Selected Elements: [20 40 50]


#### Checking If an Array is a Copy or a View

In [20]:
arr = np.array([1, 2, 3, 4])

view_arr = arr.view()
copy_arr = arr.copy()

print("View base:", view_arr.base)  # Shows the original array
print("Copy base:", copy_arr.base)  # None (independent copy)


View base: [1 2 3 4]
Copy base: None


#### Stacking NumPy Arrays (Joining Multiple Arrays)

#### Vertical Stacking (vstack)

In [21]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stacking vertically
result = np.vstack((arr1, arr2))

print("Vertical Stack:\n", result)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Horizontal Stacking (hstack)

In [22]:
result = np.hstack((arr1, arr2))
print("Horizontal Stack:\n", result)


Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


#### Column & Row Stacking (column_stack & row_stack)

In [24]:
arr1D_1 = np.array([1, 2, 3])
arr1D_2 = np.array([4, 5, 6])

# Column-wise stacking (Converts 1D arrays into 2D column vectors)
print("Column Stack:\n", np.column_stack((arr1D_1, arr1D_2)))

# Row-wise stacking (Simply stacks like hstack)
print("Row Stack:\n", np.row_stack((arr1D_1, arr1D_2)))


Column Stack:
 [[1 4]
 [2 5]
 [3 6]]
Row Stack:
 [[1 2 3]
 [4 5 6]]


/var/folders/r9/3w7hxnm53t34_s8nmmbf0tlc0000gn/T/ipykernel_34088/836325212.py:8: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print("Row Stack:\n", np.row_stack((arr1D_1, arr1D_2)))


#### Splitting NumPy Arrays (Dividing into Smaller Arrays)

#### Splitting a 1D Array

In [25]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Splitting into 3 equal parts
split_arrays = np.split(arr, 3)

print("Splitted Arrays:", split_arrays)


Splitted Arrays: [array([10, 20]), array([30, 40]), array([50, 60])]


#### Splitting a 2D Array

In [26]:
arr2D = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8]])

# Splitting along columns (axis=1)
print("Split along columns:", np.hsplit(arr2D, 2))

# Splitting along rows (axis=0)
print("Split along rows:", np.vsplit(arr2D, 2))


Split along columns: [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
Split along rows: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


#### Generating Random Integers (randint)

In [27]:
import numpy as np  

# Generate a single random integer between 1 and 100
rand_int = np.random.randint(1, 100)
print("Random Integer:", rand_int)

# Generate an array of 5 random integers between 1 and 100
rand_array = np.random.randint(1, 100, size=5)
print("Random Array:", rand_array)

# Generate a 2D array of random integers
rand_2D = np.random.randint(1, 100, size=(3, 3))
print("Random 2D Array:\n", rand_2D)


Random Integer: 45
Random Array: [71 50 12 18 15]
Random 2D Array:
 [[78 40 12]
 [75  3 59]
 [62 70 74]]


#### Generating Random Floating-Point Numbers (rand, randn)


#### rand() – Uniform Distribution (0 to 1)

In [28]:
rand_float = np.random.rand()  # Single random float
rand_floats = np.random.rand(3, 3)  # 3x3 array of random floats

print("Single Random Float:", rand_float)
print("\n3x3 Random Float Array:\n", rand_floats)


Single Random Float: 0.014063434107818074

3x3 Random Float Array:
 [[0.44978667 0.91261882 0.56211768]
 [0.83899321 0.65776808 0.79809983]
 [0.94481927 0.20481955 0.5512151 ]]


#### randn() – Standard Normal Distribution (Mean = 0, Std Dev = 1)

In [30]:
rand_norm = np.random.randn(3, 3)  # 3x3 matrix of normally distributed numbers
print("Random Normal Distribution Array:\n", rand_norm)
# Generates random numbers from a normal (Gaussian) distribution.

Random Normal Distribution Array:
 [[-0.00557609  1.65540207  0.71649616]
 [-0.43645492 -0.91707071 -1.19906368]
 [ 0.35253609  0.37815014  0.85624511]]


#### Setting a Random Seed for Reproducibility

In [34]:
np.random.seed(42)  # Setting seed for reproducibility

print("Random numbers with seed:")
print(np.random.rand(3, 3))  # Generates the same numbers every time


Random numbers with seed:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


#### Randomly Shuffling & Choosing Elements